# Generated by Django 6.0.3 on 2026-03-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employeeimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
